### ISSUE TITLE
Remirror 1.0 release roadmap

### ISSUE THREAD

**Issue by ifiokjr** [ifiokjr/remirror#1]
## Introduction

Remirror is a beautiful editor deployable to any environment. 

The foundation is Prosemirror which brings with it, years of production usage and a brilliant developer [Marijn Haverbeke](http://marijnhaverbeke.nl/) managing its future.

Here I outline the key goals for Remirror and how it can transition into something that makes developing your next text-editor fun.

<br>

### Multiplatform and multienvironment support

Remirror should be able to run anywhere a Javascript runtime exists. Examples and documentation should make it obvious how to get started in any and all environments.

The environments remirror will highlight support for are as follows.

- Modern browsers
- Server side rendering (SSR) support
- Webviews for native and mobile apps with full integration and documentation
- Desktop environments (like Electron)

For native code there should be a simple path to configuring the build to inject into the webview as well as bidirectionally passing messages between native code and the webview. The menu would be native but the actual editing experience will be DOM based.

### Modular and configurable codebase

To promote the idea of being a truly lightweight editor the codebase will be composed of building blocks meaning that users only pick the functionality they need in an editor promoting the smallest possible builds.

The packages will be namespaced under `@remirror/*`

Example packages will be as follows.

- `@remirror/core`
- `@remirror/react`
- `@remirror/extension-mention`

<br>

### High quality prebuilt solutions

As well as building blocks this repository will contain ready made packages which provide well known text editor interfaces. 

For example it should be possible to implementing the following editing UI’s with almost zero effort

- GitHub Text Editor
- Slack text editor
- Medium blog post editor

<br>

## Roadmap

<br>

- [x] Docz support #10
- [ ] ~~~Lerna changelog support (needs https://github.com/lerna/lerna-changelog/issues/128)~~~
- [x] A barebones core editing experience `@remirror/core` #10
- [x] React Hooks support
- [x] Render prop and context api support #10
- [x] Commands, actions and menu support #10
- [x] Support for custom extensions (plugins) #10
- [x] A top-level `remirror` package which combines many of the building blocks into an easy to consume npm package
- [ ] SSR support
- [ ] Electron support and some quick start examples
- [ ] Examples folder - similar to [SlateJS](https://www.slatejs.org/) and [tiptap](https://tiptap.scrumpy.io/)
- [ ] Markdown support

#### Extensions

- [ ] Emoji support with auto suggestion and floating menu
- [x] Mentions / Suggestions
- [ ] Code block support with prettier addons
- [x] Placeholder support #10
- [ ] Multicursor support
- [ ] Collaborative editing support

#### UI

 - [x] Twitter UI package
 - [ ] GitHub UI editor package
 - [ ] Medium UI editor package
 - [ ] Slack editor package
 - [ ] Wysiwyg editor

**Comment by chimon2000** [comment]
Another robust editor worth mentioning as a potential UI package is [Dropbox Paper](https://paper.dropbox.com)

**Comment by ifiokjr** [comment]
@chimon2000 Thanks for the great suggestion. 

This project is still quite a long way off from that kind of sophistication but that's definitely the direction I'd like to it head in. 

Ideally, remirror becomes a go-to for off the shelf complex text editor ui's. Collaborative editing environments like Dropbox Paper are definitely part of this goal.

**Comment by ifiokjr** [comment]
A lot has changed since creating this issue. I'll create a new issue with a pseudo plan and direction for the `remirror` project. 

Closing for now 😄

**Comment by zhaoyao91** [comment]
@ifiokjr hi, I can't find the new plan or roadmap, is it here?
