### ISSUE TITLE
Enhanced emoji support

### ISSUE THREAD

**Issue by ifiokjr** [ifiokjr/remirror#48]
Currently, this library uses emoji-mart as the provider of emoji support. However, it's not ideal since it brings in a large dependency since for some reason the build always pulls in the data.json file.

Another issue is that the emoji library uses PNGs rather than SVGs so the quality depreciates on high definition devices. 

This is a top-level issue for enabling much better emoji support 

- [ ] SVG emoji support
- [ ] An emoji picker based on the same data structure as emoji-mart
- [ ] Translation from emoji component to native string and visa-versa
- [ ] Emoticon support
- [ ] Inline emoji search queries via colons

The following libraries should be available

- [EmojiTwo](https://github.com/EmojiTwo/emojitwo/tree/master/svg)
- [Twemoji](https://github.com/twitter/twemoji/tree/gh-pages/2/svg)
- [Google Noto](https://github.com/googlei18n/noto-emoji/tree/master/svg)
- [BlobMoji](https://github.com/C1710/blobmoji/tree/master/svg)
- [OpenMoji](https://github.com/hfg-gmuend/openmoji/tree/master/color/svg)

If any SVG emoji libraries which are spec compliant come up I'll use them. Some honorable mentions which seem like hard work though are [emojidex](https://github.com/emojidex/emojidex-vectors) and [emojione](https://github.com/emojione/emojione) which is **_not free_** 😢
