### ISSUE TITLE
Android: Collation of bugs and issues

### ISSUE THREAD

**Issue by ifiokjr** [ifiokjr/remirror#53]
## Description

Use this issue as a means to collect the list of bugs noticed on Android since there are many and fixing them is proving difficult.

## Issues

- [x] ~Can't delete emoji nodes on android with any keyboard~ #15
- [x] ~Sometimes can't delete marks~ #15
- [x] ~Placeholder persists after typing starts~ #17 
- [ ] After deleting an emoji node the cursor disappears #52

**Comment by ifiokjr** [comment]
Closing as not really helpful.
